AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/**/*
    - bin/**/*

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 256

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
