name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - { ruby: "2.6", mongodb: '4.4', gemfile: 'mongoid-4.0', bundler: '2.0.0.pre.3' }
          - { ruby: "2.7", mongodb: '4.4', gemfile: 'mongoid-5.0', bundler: '2.0.0.pre.3' }
          - { ruby: "2.7", mongodb: '4.4', gemfile: 'mongoid-6.0' }
          - { ruby: "2.7", mongodb: '4.4', gemfile: 'mongoid-7.0' }
          - { ruby: "3.1", mongodb: '4.4', gemfile: 'mongoid-8.0' }
    name: test (ruby=${{ matrix.entry.ruby }}, mongodb=${{ matrix.entry.mongodb }}), gemfile=${{ matrix.entry.gemfile }})
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.entry.gemfile }}.gemfile
    steps:
      - name: Set up MongoDB ${{ matrix.entry.mongodb }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.entry.mongodb }}
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - name: Bundle install w/custom bundler
        if: ${{ matrix.entry.bundler }}
        run: |
          gem install bundler:${{ matrix.entry.bundler }}
          bundle _${{ matrix.entry.bundler }}_ install
      - name: Bundle install with default bundler
        if: ${{ !matrix.entry.bundler }}
        run: bundle install
      - name: Run tests
        run: bundle exec rake
